### ISSUE TITLE
Initial commit

### ISSUE THREAD

**Issue by maksJopek** [maksJopek/rustberry#1]
### Make initial commit

- [x] Create README.md
- [x] Make LICENSE and set it on Github ( AGPL-3-or-later )
- [x] Add .gitignore ( some general stuff )
- [x] Add shell script to automatically make branches from issues using GithubCli
- [x] Create directory tree for backend & frontend ( nginx config has to be included somewhere )

**Comment by c-a-v-a** [comment]
#### [Started work on branch feature/RB-1|Initial-commit](https://github.com/maksJopek/rustberry/tree/feature/RB-1|Initial-commit)
