### ISSUE TITLE
Initiate backend

### ISSUE THREAD

**Issue by maksJopek** [maksJopek/rustberry#2]
### Create start of actix api server

- [x] Initiate new rust project in backend directory
- [x] Create directory tree for backend
- [x] Create main function which starts actix server with tls ( add test certificate and set paths for production one )
- [x] Make url's list

**Comment by c-a-v-a** [comment]
#### Started work on branch [feature/RB-2|Initiate-backend](https://github.com/maksJopek/rustberry/tree/feature/RB-2|Initiate-backend)
