### ISSUE TITLE
Create login page

### ISSUE THREAD

**Issue by maksJopek** [maksJopek/rustberry#29]
- [ ] Simple login page with inputs for login and password
- [ ] Footer with information about rustberry, license and link to github
- [ ] Decide if the login page should be independent from rest of the app, if so then it could be simple HTML site without any JS

**Comment by chien-b1812825** [comment]
I think, I can solve it. can u assign it to me ? I need ur reply to complete my homework. Thanks

**Comment by henryjohn1011** [comment]
Assign me. I think i can solve it. Thank you

**Comment by maksJopek** [comment]
Hi @chien-b1812825 and @henryjohn1011 !
I'm very glad that you want to support rustberry, you can both create branch and than PR which I will review and merge. We have script for making branches in /bin, I will suggest to person that will be second to take this issue to take another task or make second branch with name feature/RB-29|Create-login-page|2

**Comment by chien-b1812825** [comment]
@maksJopek , I have a problem when I create a new branch.
![image](https://user-images.githubusercontent.com/91580551/141262878-26a83a2b-44bf-4cfa-a86d-26bcf6a8ff08.png)

**Comment by maksJopek** [comment]
Sorry to hear that, I think that you're running Windows and scripts were tested on Linux, maybe there's problem with | ( pipe ) character, when I searched Internet for this error I found [something](https://stackoverflow.com/questions/6656619/git-and-nasty-error-cannot-lock-existing-info-refs-fatal), maybe it would help you.

**Comment by chien-b1812825** [comment]
I'm sorry, but I need your feedback to complete my homework. I have to report to my teacher next week. Thank you so much !

**Comment by maksJopek** [comment]
@chien-b1812825 I don't think I understand what happen, but you're welcome.
